# checkov-config.yaml

# Define which policies to run (Azure-focused checks)
check:
  - CKV_AZURE_1       # Ensure that no Azure Virtual Machine has password authentication enabled
  - CKV_AZURE_75      # Ensure that Azure Data Explorer uses double encryption
  - CKV_AZURE_11      # Ensure that 'Secure transfer required' is enabled for Azure Storage Accounts
  - CKV_AZURE_14      # Ensure that SQL servers have an Azure Active Directory admin set
  - CKV_AZURE_25      # Ensure AKS logging to Azure Monitoring is configured

# Define checks to skip (optional)
skip-check:
  - CKV_AZURE_3       # Example: skip check for Azure Storage Accounts with public access
  - CKV_AZURE_4       # Example: skip check for SQL Server firewall rules allowing all IPs

# Configure output settings
output:
  - cli             # Use `cli` for standard console output
  - json            # Output a JSON file
  - junitxml        # Produce JUnit XML for integration with test tools

output_path: "./checkov_report.json"  # The output file path for JSON format

# Set severity threshold (optional)
severity: HIGH           # Options: LOW, MEDIUM, HIGH, CRITICAL

# Enable or disable resource tagging (helpful for identifying where checks apply)
resource_tagging:
  enabled: true
  tags:
    - "team:CTRDEV"
    - "environment:production"

# Customize the reporting behavior
report:
  suppress_warnings: true  # Suppress warning messages in the output
  summary: true            # Show summary at the end of the output
  compact: false           # Full details instead of compact format

# Logging level (optional)
logging:
  level: ERROR  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# Filter checks by framework
framework:
  - terraform           # Limit the scan to only Terraform files
  - azure               # Azure-specific framework

# Exclude directories
directory-exclude:
  - .git                # Ignore the .git directory
  - .terraform          # Ignore Terraform's hidden files
  - test                # Ignore test directory
  - examples            # Ignore example files

# Allow custom rules (if you have custom Checkov rules)
custom-rules:
  path: ./custom_checks  # Define a path where custom Checkov rules are located

# Define environment-specific configurations
environment:
  production:
    skip-check:
      - CKV_AZURE_11   # Example: skip 'Secure transfer required' in production for certain scenarios
  development:
    check:
      - CKV_AZURE_15   # Example: enforce checks for secure transfer in development
      - CKV_AZURE_13   # Ensure that Azure Cosmos DB accounts use private endpoints
