# checkov-config.yaml

# Define which policies to run (Azure-focused checks)
check:
  - CKV_AZURE_1       # Ensure that no Azure Virtual Machine has password authentication enabled
  - CKV_AZURE_75      # Ensure that Azure Data Explorer uses double encryption
  - CKV_AZURE_11      # Ensure that 'Secure transfer required' is enabled for Azure Storage Accounts
  - CKV_AZURE_14      # Ensure that SQL servers have an Azure Active Directory admin set
  - CKV_AZURE_25      # Ensure AKS logging to Azure Monitoring is configured

# Define checks to skip (optional)
skip-check:
  - CKV_AZURE_3       # Skip check for Azure Storage Accounts with public access
  - CKV_AZURE_4       # Skip check for SQL Server firewall rules allowing all IPs

# Configure output settings for CLI use
output:
  format: cli         # Specify CLI output
output-file-path: ./checkov_report.json  # Specify path for JSON output file

# Severity threshold (if supported by CLI usage)
severity: HIGH        # Filter checks with a minimum severity level

# Enable framework filtering to only Terraform and Azure resources
framework:
  - terraform
  - azure

# Exclude directories
directory-exclude:
  - .git
  - .terraform
  - test
  - examples