# checkov-config.yaml

# Define which policies to run (Azure-focused checks)
check:
  - CKV_AZURE_1       # Ensure that no Azure Virtual Machine has password authentication enabled
  - CKV_AZURE_75      # Ensure that Azure Data Explorer uses double encryption
  - CKV_AZURE_11      # Ensure 'Secure transfer required' is enabled for Azure Storage Accounts
  - CKV_AZURE_180     # Ensure additional Azure checks are enforced as needed
  - CKV_AZURE_173     # Ensure API management uses at least TLS 1.2
  - CKV_AZURE_223     # Ensure Event Hub Namespace uses at least TLS 1.2
  - CKV_AZURE_62      # Ensure function apps are not accessible from all regions
  - CKV_AZURE_145     # Ensure Function app is using the latest version of TLS encryption
  - CKV_AZURE_159     # Ensure function app builtin logging is enabled
  - CKV_AZURE_111     # Ensure that key vault enables soft delete

# Define checks to skip (optional)
skip-check:
  - CKV_AZURE_3       # Skip check for HTTPS traffic enforcement on Azure Storage Accounts
  - CKV_AZURE_4       # Skip check for SQL Server firewall rules allowing all IPs