# checkov-config.yaml

# Define essential policies to run (basic Azure-focused checks)
check:
  - CKV_AZURE_1       # Ensure no Azure VM has password authentication enabled
  - CKV_AZURE_11      # Ensure 'Secure transfer required' is enabled for Azure Storage Accounts
  - CKV_AZURE_12      # Ensure managed identity authentication is enabled for App Service and Functions
  - CKV_AZURE_13      # Ensure Cosmos DB accounts use private endpoints
  - CKV_AZURE_14      # Ensure SQL servers have an Azure AD admin set

# Define checks to skip (optional)
# Skip any checks that are irrelevant or causing issues for basic validation
skip-check:
  - CKV_AZURE_3       # Skip check for Azure Storage Accounts with public access
  - CKV_AZURE_4       # Skip check for SQL Server firewall rules allowing all IPs

# Output format for the report (basic CLI output)
output:
  format: cli        # Use CLI for local readability

# Framework filtering - only scan Terraform files and Azure resources
framework:
  - terraform
  - azure

# Exclude unnecessary directories
directory-exclude:
  - .git             # Exclude the .git directory
  - .terraform       # Exclude Terraform's hidden files