# checkov-config.yaml

# Define which policies to run (Azure-focused checks)
check:
  - CKV_AZURE_1       # Example: Ensure that no Azure Virtual Machine has password authentication enabled
  - CKV_AZURE_75      # Example: Ensure that Azure Data Explorer uses double encryption
  - CKV_AZURE_11      # Example: Ensure 'Secure transfer required' is enabled for Azure Storage Accounts
  - CKV_AZURE_180     # Add any additional Azure checks as needed
  - CKV_AZURE_173

# Define checks to skip (optional)
skip-check:
  - CKV_AZURE_3       # Example: skip check for Azure Storage Accounts with public access
  - CKV_AZURE_4       # Example: skip check for SQL Server firewall rules allowing all IPs
